### ISSUE TITLE
Blurred background when Modal is opened shifts down 

### ISSUE THREAD

**Issue by PerryCodes** [joadan/TabBlazor#9] opened 2021-07-03 15:39 UTC
Whenever I open a modal, the blurred background appears to move down about 10 or 15 px.  Can that be adjusted?

**Comment by joadan** [comment] 2021-07-06 10:51
Hi,

Sorry but I'm not able to reproduce this.
Do you see this in the demo page [Model Demo](https://tabblazor.com/docs/modals)?

**Comment by joadan** [comment] 2021-10-03 07:39
Fixed in v0.4.4-alpha

**Closed by joadan** 2021-10-03 07:39 UTC
